### ISSUE TITLE
Tests fail on 64-bit Ubuntu 17.10

### ISSUE THREAD

**Issue by jcw** [carld/micro-lisp#19]
As the title says. I get several warnings from gcc 7.2.0, but they appear harmless. Could it be due to the 64-bit environment, where pointers are larger than plain ints? I haven't looked closer yet...

**Comment by jcw** [comment]
To follow up, after adding a symlink from micro-lisp to micro-flisp, `test.sh` passes the first 19 of 40 tests (vs 0 passed in the make). The first failure is:

    ((lambda (f x) (f)) ((lambda (x) (lambda () x)) (quote x)) (quote y)) -> x

**Comment by carld** [comment]
@jcw that test passes for the mlisp89 version which supports closures properly.  Closures like that weren't implemented in the original micro-lisp. Happy to take a PR though!
