### ISSUE TITLE
Pointer tagging cast using long

### ISSUE THREAD

**Issue by jibsen** [carld/micro-lisp#2]
Pointers and `long` are not necessarily the same size (on 64-bit Windows `long` is 32-bit). It might be a good idea to use `uintptr_t` if available, or check that the size of the integer matches that of a pointer.

**Comment by carld** [comment]
Hey @jibsen thanks for the comment, I didn't know that about Windows. I replaced `long` with `uintptr_t` and it compiled fine for me on OSX. 👍

**Comment by jibsen** [comment]
Thanks!
