### ISSUE TITLE
Error : mlisp89.c:508: undefined reference to `funopen'

### ISSUE THREAD

**Issue by faiz-lisp** [carld/micro-lisp#20]
Error : mlisp89.c:508: undefined reference to `funopen'

The funopen may be just for BSD OS.
I am on MINGW32_NT-10.0 (msys2), and run into the error case!

**Comment by Islam0mar** [comment]
should work after pull request with `make non-bsd` with [libbsd](https://github.com/cygwinports-extras/libbsd) installed.

**Comment by faiz-lisp** [comment]
Many thanks to you~ @Islam0mar

**Comment by Islam0mar** [comment]
You are welcome :+1:
