### ISSUE TITLE
examples/format.lisp is missing?

### ISSUE THREAD

**Issue by cellularmitosis** [carld/micro-lisp#23]
Thank you so much for publishing this project!

I ran `test.sh` and found a problem:

```
examples/format.lisp -> hello 21553 test world
#t
cat: examples/format.lisp: No such file or directory
Test FAIL
```

Sure enough, there is no `format.lisp` file in the `examples/` directory.

**Comment by carld** [comment]
Hey, thanks for noticing. I found the file. I've changed macbooks since and a bunch of stuff but I think these commits also fix #24
