### ISSUE TITLE
cannot lookup: null

### ISSUE THREAD

**Issue by cellularmitosis** [carld/micro-lisp#24]
Hello,

I ran into an issue when running the REPL with mlisp89:

```
$ cat repl.lisp - | ./mlisp89
cannot lookup: null
(+ 1 1)
$ echo $?
1
```

I tried adding null to the "environment", but it didn't seem to work.  Do I need to implement support for this directly in eval?

**Comment by carld** [comment]
this is interesting; I can't recall much about this; I found some code that looks like it addresses this. The tests passed for me.

**Comment by carld** [comment]
Hey, yeah your suggestion was on the right track, I had a commit on my laptop that added null to `builtin_lib` 

https://github.com/carld/micro-lisp/blob/master/mlisp89.c#L442

null is the same as (quote ()) in this implementation apparently

the builtin_lib was a way to implement more of the language in the language itself to minimise the C code.

enjoy
