### ISSUE TITLE
Bound checks for gettoken()

### ISSUE THREAD

**Issue by mar77i** [carld/micro-lisp#3]
By the power of SIGSEGV, **please** bound-check index in `gettoken()`.

**Comment by carld** [comment]
Hey @mar77i , good catch, if `index` makes it to 32, things like that can happen.

**Comment by carld** [comment]
f05c552ae71a8615536d25c49dd4ad0a8e298195
3b9019495ebc1822445a3411e59b9d0d7dd2a607
