### ISSUE TITLE
print_obj() has curious if-statement

### ISSUE THREAD

**Issue by raldi** [carld/micro-lisp#9]
At https://github.com/carld/micro-lisp/blob/ff5472f56415cf961c47efb0320d31e82c8fc401/micro-lisp.c#L75 we have a section of code that reads:

```
    if (cdr(ob) != 0) {
      if (is_pair(cdr(ob))) {  printf(" "); print_obj(cdr(ob), 0);  }
    }
```

That inner `is_pair()` looks like a possible mistake -- the prior line ensures that this if-statement only gets evaluated if `cdr(ob)` is non-nil, but in that case, how could `is_pair(cdb(ob))` ever be false? In micro-lisp, the CDR is always a (possibly-empty) list, is it not?

Even if it were possible for the CDR to be a non-list, wouldn't you want an `else` statement for this `if`, to print something else when that's the case?

**Comment by carld** [comment]
Hey @raldi yep the `next` field will be either 0 or a `List *` so checking the tag is redundant 👍

**Comment by carld** [comment]
6a728a3fd9479c499d777b9c3b6e5cced5eddb46 fixes
